export const WORKFLOW_TEMPLATES = [
  {
    id: 'home-loan',
    name: 'Home Loan Application',
    description: 'Apply for a home loan at any bank',
    category: 'Finance',
    requiredDocuments: ['PAN_CARD', 'AADHAAR_CARD', 'SALARY_SLIP', 'BANK_STATEMENT'],
    optionalDocuments: ['ITR', 'SALE_DEED'],
    estimatedTime: '15-20 minutes',
  },
  {
    id: 'business-incorporation',
    name: 'Company Incorporation',
    description: 'Register a private limited company with MCA',
    category: 'Business',
    requiredDocuments: ['PAN_CARD', 'AADHAAR_CARD', 'ELECTRICITY_BILL'],
    optionalDocuments: [],
    estimatedTime: '30-45 minutes',
  },
  {
    id: 'passport-renewal',
    name: 'Passport Renewal',
    description: 'Renew your Indian passport',
    category: 'Government',
    requiredDocuments: ['PASSPORT', 'AADHAAR_CARD', 'PAN_CARD'],
    optionalDocuments: [],
    estimatedTime: '20-30 minutes',
  },
  {
    id: 'gst-registration',
    name: 'GST Registration',
    description: 'Register for GST as a new business',
    category: 'Business',
    requiredDocuments: ['PAN_CARD', 'AADHAAR_CARD', 'BANK_STATEMENT', 'ELECTRICITY_BILL'],
    optionalDocuments: ['INCORPORATION_CERTIFICATE'],
    estimatedTime: '25-35 minutes',
  },
  {
    id: 'driving-license-renewal',
    name: 'Driving License Renewal',
    description: 'Renew your driving license at the transport office',
    category: 'Government',
    requiredDocuments: ['DRIVING_LICENSE', 'AADHAAR_CARD', 'PAN_CARD'],
    optionalDocuments: [],
    estimatedTime: '15-20 minutes',
  },
];
